//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.BookingRooms = new HashSet<BookingRooms>();
        }
    
        public int ID { get; set; }
        public bool FullPayment { get; set; }
        public int Agent { get; set; }
        public int Client { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime Arrival { get; set; }
        public System.DateTime Departure { get; set; }
        public Nullable<int> Receipt { get; set; }
        public string C_Contract { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Actor Actor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRooms> BookingRooms { get; set; }
        public virtual Receipt Receipt1 { get; set; }
    }
}
