//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingRooms
    {
        public int BookingID { get; set; }
        public int Room { get; set; }
        public bool Type { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
