//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaning
    {
        public int ID { get; set; }
        public int Room { get; set; }
        public int ChangeID { get; set; }
        public System.DateTime Today { get; set; }
        public int Actor { get; set; }
    
        public virtual Actor Actor1 { get; set; }
        public virtual Change Change { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
