//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hosteldat2Entities : DbContext
    {
        public hosteldat2Entities()
            : base("name=hosteldat2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<BookingRooms> BookingRooms { get; set; }
        public virtual DbSet<Change> Change { get; set; }
        public virtual DbSet<Cleaning> Cleaning { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<Request> Request { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RoomClass> RoomClass { get; set; }
        public virtual DbSet<RoomEating> RoomEating { get; set; }
        public virtual DbSet<RoomWindow> RoomWindow { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Room> Room { get; set; }
        public virtual DbSet<EventRooms> EventRooms { get; set; }
        public virtual DbSet<TempRooms> TempRooms { get; set; }
    }
}
