//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.BookingRooms = new HashSet<BookingRooms>();
            this.Cleaning = new HashSet<Cleaning>();
            this.EventRooms = new HashSet<EventRooms>();
        }
    
        public int RoomNum { get; set; }
        public Nullable<int> Places { get; set; }
        public string CategoryClass { get; set; }
        public string CategoryWindow { get; set; }
        public string CategoryEating { get; set; }
        public int C_Floor { get; set; }
        public decimal cost { get; set; }
        public bool dirty { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingRooms> BookingRooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cleaning> Cleaning { get; set; }
        public virtual RoomClass RoomClass { get; set; }
        public virtual RoomEating RoomEating { get; set; }
        public virtual RoomWindow RoomWindow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventRooms> EventRooms { get; set; }
    }
}
